version: '3.8'

services:
  app:
    image: ${IMAGE_NAME}
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_PUBLIC_KEY=${DISCORD_PUBLIC_KEY}
      - DISCORD_REDIRECT_URI=https://${COOLIFY_FQDN}/api/auth/discord/callback
      - SESSION_SECRET=${SESSION_SECRET}
      - AUTH_COOKIE_SECURE=true
      - AUTH_COOKIE_SAME_SITE=lax
      - USE_MEMORY_STORAGE=true
    ports:
      - "${PORT}:5000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/auth/status"]
      interval: 10s
      timeout: 5s
      retries: 5
